#!/usr/bin/env bash
# A script that configures the server using a redirection file
apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/H-Asmaa permanent;\/" /etc/nginx/sites-enabled/default
nginx -t
systemctl restart nginx
