#!/usr/bin/env bash
# A script that configures the server using a redirection file
apt-get update -y
apt-get install nginx -y
sudo sed -i "46i rewrite /redirect_me https://intranet.alxswe.com/ permanent;" /etc/nginx/sites-available/default
nginx -t
systemctl restart nginx
