#!/usr/bin/env bash
# A script that configures a new server and configure it to contain a custom header.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/index.nginx-debian.html
sudo sed -i "46i rewrite ^/redirect_me https://intranet.alxswe.com/ permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i "46i error_page /custom_404.html;" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/ a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
