#!/usr/bin/env bash
# A script that configures the load balancer.
apt-get -y update
apt-get install haproxy -y
echo '
frontend my_frontend
        bind 0:80
        default_backend web_servers

backend my_backend
        balance roundrobin
        server 376576-web-01 18.207.139.124:80
        server 376576-web-02 54.236.45.101:80
' >> /etc/haproxy/haproxy.cfg
service haproxy restart
