#!/usr/bin/env bash
# A script that generates a MySQL dump and creates a compressed archive out of it.
sudo mysqldump -u root -p"$1" --all-databases | sudo tee backup.sql
tar -czf "$(date +'%d-%m-%Y').tar.gz" backup.sql
