#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
	# display hours from 0 to 12
	# display minutes from 1 to 59
counter=1
hour=1
echo "Hour: 0"
while [ $counter -le 59 ]
do
	if [ $counter -eq 59 ];then
		echo "$counter"
		if [ $hour -ne 13 ];then
			echo "Hour: $hour"
		fi
		counter=0
		((hour++))
		if [ $hour -eq 14 ];then
			break
		fi
	else
		echo "$counter"
	fi
	((counter++))
done
