#!/usr/bin/env bash
# A script that is running as nginx user and configuring nginx to listen on all the active IPs on port 8080.
sudo sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
