#!/usr/bin/env bash
# A script that is running as nginx user and configuring nginx to listen on all the active IPs on port 8080.
sudo sed -i 's/user\s*[^;]/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/Listen 80;/Listen *:8080;' /etc/nginx/nginx.conf
sudo -u nginx service nginx start
